### ISSUE TITLE
Publish Calculated Data?

### ISSUE THREAD

**Issue by NBPub** [Puntalytics/puntr-data#1]
Request for non-R users:

Would it be possible publish cleaned punt data with calculated RERUN, SHARP, pEPA, and other relevant punt statistics? Thanks for the great punting research.

edit: copied issue [here](https://github.com/Puntalytics/puntr/issues/13)

**Comment by dennisbrookner** [comment]
I just pushed new versions of all of the data, in both `.rds` and `.csv.gz` format, which include all of the calculated stats! They currently live on the `updates` branch; let me know if it all looks good, and I'll merge it into main!

I also added a lil script which is what I used to create all the files. In theory, I could make this run as a workflow on this repo, but in the mean time, I guess I'll just periodically update it manually. That means that the 2022 data is partial and not being autoupdated!

https://github.com/Puntalytics/puntr-data/tree/update

**Comment by NBPub** [comment]
Awesome, I'll check it out today and see if I get a chance to update my [project](https://nbpub.github.io/TitanUp/#scrollspyPunt). Thank you!

**Comment by nishantbb** [comment]
Please let me know when you update through the 2022 regular season, thanks!

**Comment by NBPub** [comment]
The data looks good! I was able to extract the various SHARPs and pEPAs and add them to my existing punter data. 

Please let me know when you update through the 2022 regular season, thanks!
